### ISSUE TITLE
java.net.ConnectException when trying to connect through http proxy with authentication

### ISSUE THREAD

**Issue by phoenixzero2** [GeertjanWielenga/SpringBootTools4NetBeans#5]
Hi everyone:
I just downloaded the spring tools for netbeans in my company. Unfortunately I receive an error when trying to start the Spring Boot Initializr project. Need to point out that my company has an http proxy with authentication. I already setup the proxy configuration in netbeans and confirmed that the connection has been successful:

Caused: java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:988)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:986)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java:713)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:985)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
    at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78)
    at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
    at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:619)
Caused: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://start.spring.io": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:633)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:595)
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:557)
    at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrService.getMetadata(InitializrService.java:68)
    at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrProjectWizardPanel1.getInitializrMetadata(InitializrProjectWizardPanel1.java:122)
[catch] at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrProjectPanelVisual1.construct(InitializrProjectPanelVisual1.java:332)
    at org.openide.util.AsyncInitSupport.run(AsyncInitSupport.java:168)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

Thanks in advance for this great tool and if there's something I can help, I'll be glad to do it.

Phoenixzero2

**Comment by phoenixzero2** [comment]
Hi again

Forgot to mention my current application details:

Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_45; Java HotSpot(TM) Client VM 25.45-b02
Runtime: Java(TM) SE Runtime Environment 1.8.0_45-b15
System: Windows 7 version 6.1 running on x86; Cp1252; en_US (nb)

If you need more details, don't hesitate in contact me. 

Warm regards.
Phoenixzero2
